[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/tutorial"
  to = "/tutorial.html"
  status = 200

# For any other path that doesn't exist, serve the index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
